language: cpp
sudo: true
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - gcc-6
  homebrew:
    taps:
      - facebook/fb
    packages:
      - buck

os:
  - linux
  - osx

env:
  - BUCKAROO_VERSION=buckaroo-redux-alpha-13

cache:
  directories:
    - $HOME/.buckaroo/cache

osx_image: xcode9.3

before_install:
  - ./travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - ./buckaroo-client install
  - buck build -c ui.superconsole=DISABLED //:immer
  - buck run -c ui.superconsole=DISABLED //example/array
  - buck run -c ui.superconsole=DISABLED //example/box
  - buck run -c ui.superconsole=DISABLED //example/flex-vector
  - buck run -c ui.superconsole=DISABLED //example/map
  - buck run -c ui.superconsole=DISABLED //example/set
  - buck run -c ui.superconsole=DISABLED //example/vector
